/*
 * 
 */

package uy.red.pge.servicios.agesic.artee.enviarexpediente;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Nov 21 10:14:28 UYT 2017
 * Generated source version: 2.3.1-patch-01
 */

@WebServiceClient(name = "ServiceSendExpedientStream",
				  wsdlLocation = "file:/home/abrusco/Descargas/EnviarExpediente.wsdl",
				  targetNamespace = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente")
public class ServiceSendExpedientStream extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://servicios.pge.red.uy/agesic/artee/EnviarExpediente",
			"ServiceSendExpedientStream");
	public final static QName CustomBindingServicioEnviarExpediente = new QName(
			"http://servicios.pge.red.uy/agesic/artee/EnviarExpediente", "CustomBinding_ServicioEnviarExpediente");

	static {
		URL url = null;
		try {
			url = new URL("file:/home/abrusco/Descargas/EnviarExpediente.wsdl");
		}
		catch (MalformedURLException e) {
			System.err.println("Can not initialize the default wsdl from file:/home/abrusco/Descargas/EnviarExpediente.wsdl");
			// e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public ServiceSendExpedientStream(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ServiceSendExpedientStream(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceSendExpedientStream() {
		super(WSDL_LOCATION, SERVICE);
	}

	public ServiceSendExpedientStream(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public ServiceSendExpedientStream(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public ServiceSendExpedientStream(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * @return returns ServicioEnviarExpediente
	 */
	@WebEndpoint(name = "CustomBinding_ServicioEnviarExpediente")
	public ServicioEnviarExpediente getCustomBindingServicioEnviarExpediente() {
		return super.getPort(CustomBindingServicioEnviarExpediente, ServicioEnviarExpediente.class);
	}

	/**
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns ServicioEnviarExpediente
	 */
	@WebEndpoint(name = "CustomBinding_ServicioEnviarExpediente")
	public ServicioEnviarExpediente getCustomBindingServicioEnviarExpediente(WebServiceFeature... features) {
		return super.getPort(CustomBindingServicioEnviarExpediente, ServicioEnviarExpediente.class, features);
	}

}
