package uy.red.pge.servicios.agesic.artee.enviarexpediente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Nov 21 10:14:28 UYT 2017
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente", name = "ServicioEnviarExpediente")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.arteeservicelibrary.ObjectFactory.class, uy.red.agesic.wsdl.arteeserviceswsdl.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicioEnviarExpediente {

    @WebMethod(operationName = "EnviarExpediente", action = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente/ServicioEnviarExpediente/EnviarExpediente")
    @Action(input = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente/ServicioEnviarExpediente/EnviarExpediente", output = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente/ServicioEnviarExpediente/EnviarExpedienteResponse")
    @WebResult(name = "EnviarExpedienteOut", targetNamespace = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente", partName = "parameters")
    public EnviarExpedienteOut enviarExpediente(
        @WebParam(partName = "parameters", name = "EnviarExpedienteIn", targetNamespace = "http://servicios.pge.red.uy/agesic/artee/EnviarExpediente")
        EnviarExpedienteIn parameters
    );
}
