apply plugin: 'war'

repositories {
    flatDir {
        dirs 'libs'
    }
}

def httpClientVersion = '4.5.3'
def commonsIoVersion = '2.6'
def mailVersion = '1.4'
def cxfVersion = '3.2.1'
def mockitoVersion = '1.9.5'
def wss4jVersion = '1.6.19'
def openSamlVersion = '2.6.4'
def soapApiVersion = '1.4.0'
def jaxwsApiVersion = '2.3.1'
def jwsApiVersion = '1.1'
def saajImplVersion = '1.5.1'
def annotationVersion = '1.3.2'

sourceSets {
    integrationTest {
        java.srcDir file('src/integTest/java')
        resources.srcDir file('src/integTest/resources')
        compileClasspath = sourceSets.main.output + sourceSets.test.output + configurations.testRuntime
        runtimeClasspath = output + compileClasspath
    }
}

dependencies {
    compile project(':connector-services')
    compile "org.springframework.integration:spring-integration-http:$springVersion"
    compile "org.springframework.integration:spring-integration-jmx:$springVersion"
    compile "org.apache.httpcomponents:httpclient:$httpClientVersion"
    compile "commons-io:commons-io:$commonsIoVersion"
    compile "org.opensaml:opensaml:$openSamlVersion"
    compile "org.apache.ws.security:wss4j:$wss4jVersion"
    compile "javax.mail:mail:$mailVersion"
    compile "javax.xml.soap:javax.xml.soap-api:$soapApiVersion"
    compile "javax.xml.ws:jaxws-api:$jaxwsApiVersion"
    compile "javax.jws:javax.jws-api:$jwsApiVersion"
    compile "com.sun.xml.messaging.saaj:saaj-impl:$saajImplVersion"
    compileOnly "javax.annotation:javax.annotation-api:$annotationVersion"

    testCompile "junit:junit:$junitVersion"
    testCompile "org.hamcrest:hamcrest-library:$hamcrestVersion"
    testCompile "org.apache.cxf:cxf-core:$cxfVersion"
    testCompile "org.apache.cxf:cxf-rt-frontend-jaxws:$cxfVersion"
    testCompile "org.apache.cxf:cxf-rt-transports-http:$cxfVersion"
    testCompile "org.mockito:mockito-all:$mockitoVersion"
    providedCompile "javax.servlet:javax.servlet-api:$servletApiVersion"
    compile fileTree(dir: 'libs', include: ['*.jar'])
}

test {
    exclude '**/*IntegTest.class'
    reports.html.destination = file("$reports.html.destination/unit")
    reports.junitXml.destination = file("$reports.junitXml.destination/unit")
}

task integrationTest(type: Test) {
    include '**/*IntegTest.class'
    reports.html.destination = file("$reports.html.destination/integration")
    reports.junitXml.destination = file("$reports.junitXml.destination/integration")
    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath
}

war {
    archiveFileName = 'connector-runtime.war'
}

def filesToCopy = copySpec {
    from "$buildDir/libs/${war.archiveFileName.get()}"
}

// Copy war to server
task copyWarFile {
    dependsOn build
    doLast {
        if (wildflyDeployment.startsWith("null")) {
            print("Wildfly Home not found. Define gradle connector-integration:deploy -Denvironment=develop -Dwildfly.home='complete with wildfly location'")
        } else {
            print("Copy $filesToCopy to $wildflyDeployment\n")
            copy {
                with filesToCopy
                into wildflyDeployment
            }
        }

        if (tomcatDeployment.startsWith("null")) {
            print("Tomcat Home not found. Define gradle connector-integration:deploy -Denvironment=develop -Dtomcat.home='complete with tomcat location'")
        } else {
            def newName = "ROOT.war"
            print("Copy $filesToCopy to $tomcatDeployment and rename it as $newName\n")
            copy {
                with filesToCopy
                into tomcatDeployment
                rename { newName }
            }
        }
    }
}

tasks.build.finalizedBy copyWarFile