/*
 * 
 */

package uy.red.pge.servicios.agesic.artee.descargarexpediente;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Nov 21 11:30:17 UYT 2017
 * Generated source version: 2.3.1-patch-01
 */

@WebServiceClient(name = "ServiceDownloadExpedient",
				  wsdlLocation = "file:/home/abrusco/Descargas/DescargarExpediente.wsdl",
				  targetNamespace = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente")
public class ServiceDownloadExpedient extends Service {

	public final static URL WSDL_LOCATION;
	public final static QName SERVICE = new QName("http://servicios.pge.red.uy/agesic/artee/DescargarExpediente",
			"ServiceDownloadExpedient");
	public final static QName CustomBindingServicioDescargarExpediente = new QName(
			"http://servicios.pge.red.uy/agesic/artee/DescargarExpediente", "CustomBinding_ServicioDescargarExpediente");

	static {
		URL url = null;
		try {
			url = new URL("file:/home/abrusco/Descargas/DescargarExpediente.wsdl");
		}
		catch (MalformedURLException e) {
			System.err.println("Can not initialize the default wsdl from file:/home/abrusco/Descargas/DescargarExpediente.wsdl");
			// e.printStackTrace();
		}
		WSDL_LOCATION = url;
	}

	public ServiceDownloadExpedient(URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ServiceDownloadExpedient(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceDownloadExpedient() {
		super(WSDL_LOCATION, SERVICE);
	}

	public ServiceDownloadExpedient(WebServiceFeature... features) {
		super(WSDL_LOCATION, SERVICE, features);
	}

	public ServiceDownloadExpedient(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, SERVICE, features);
	}

	public ServiceDownloadExpedient(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * @return returns ServicioDescargarExpediente
	 */
	@WebEndpoint(name = "CustomBinding_ServicioDescargarExpediente")
	public ServicioDescargarExpediente getCustomBindingServicioDescargarExpediente() {
		return super.getPort(CustomBindingServicioDescargarExpediente, ServicioDescargarExpediente.class);
	}

	/**
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
	 * @return returns ServicioDescargarExpediente
	 */
	@WebEndpoint(name = "CustomBinding_ServicioDescargarExpediente")
	public ServicioDescargarExpediente getCustomBindingServicioDescargarExpediente(WebServiceFeature... features) {
		return super.getPort(CustomBindingServicioDescargarExpediente, ServicioDescargarExpediente.class, features);
	}

}
