package uy.red.pge.servicios.agesic.artee.descargarexpediente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Tue Nov 21 11:30:17 UYT 2017
 * Generated source version: 2.3.1-patch-01
 * 
 */
 
@WebService(targetNamespace = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente", name = "ServicioDescargarExpediente")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.arteeservicelibrary.ObjectFactory.class, ObjectFactory.class, uy.red.agesic.wsdl.arteeserviceswsdl.ObjectFactory.class, org.datacontract.schemas._2004._07.arteedatacontract.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ServicioDescargarExpediente {

    @WebMethod(operationName = "DescargarExpediente", action = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente/ServicioDescargarExpediente/DescargarExpediente")
    @Action(input = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente/ServicioDescargarExpediente/DescargarExpediente", output = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente/ServicioDescargarExpediente/DescargarExpedienteResponse")
    @WebResult(name = "DescargarExpedienteOut", targetNamespace = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente", partName = "parameters")
    public DescargarExpedienteOut descargarExpediente(
        @WebParam(partName = "parameters", name = "DescargarExpedienteIn", targetNamespace = "http://servicios.pge.red.uy/agesic/artee/DescargarExpediente")
        DescargarExpedienteIn parameters
    );
}
