plugins {
    id "org.gretty" version "3.0.5"
}
apply plugin: 'war'
apply plugin: 'jacoco'

def jstlVersion = "1.2"

dependencies {
    compile project(':connector-services')
    compile "org.springframework:spring-webmvc:$springVersion"
    compile "javax.servlet:jstl:$jstlVersion"
    compile "org.springframework.security:spring-security-web:$springSecurityVersion"
    compile "org.springframework.security:spring-security-config:$springSecurityVersion"
    compile "commons-fileupload:commons-fileupload:$fileUploadVersion"

    testCompile "org.springframework:spring-test:$springVersion"
    //exclude the build in hamcrest
    testCompile("junit:junit:$junitVersion") {
        exclude group: 'org.hamcrest'
    }
    testCompile "org.hamcrest:hamcrest-library:$hamcrestVersion"
    //include in compile only, exclude in the war
    providedCompile "javax.servlet:javax.servlet-api:$servletApiVersion"
}

war {
    archiveFileName = 'connector-web.war'
}

gretty {
    httpPort = 8082
    contextPath = 'connector-web'
    servletContainer = 'tomcat85' //jetty9
}

jacoco {
    toolVersion = "0.7.5+"
    reportsDir = file("$buildDir/reports/jacoco")
}

jacocoTestReport {
    reports {
        xml.enabled = true
        html.enabled = true
    }
}

def filesToCopy = copySpec {
    from "$buildDir/libs/${war.archiveFileName.get()}"
}

task copyWarFile {
    dependsOn build
    doLast {
        [wildflyDeployment, tomcatDeployment].each { dest ->
            if (dest.startsWith("null")) {
                print("Unable to copy .war file. Server Home not set. Skipped\n")
            } else {
                print("Copy $filesToCopy to $dest\n")
                copy {
                    with filesToCopy
                    into dest
                }
            }
        }
    }
}

tasks.build.finalizedBy copyWarFile