# IP y puertos para publicar/consumir el servicio
connector.http.client.ip=localhost
connector.http.client.port.prod=9700
connector.http.client.port.test=9800
connector.http.client.port.prod.ssl=8443
connector.http.client.port.test.ssl=8553

# Timeout in miliseconds
connector.http.client.request.timeout=30000

connector.datasource.initial-pool-size=10
connector.datasource.min-pool-size=10
connector.datasource.max-pool-size=20
connector.datasource.max-statements=10
connector.datasource.max-idle-time=120

# Maximo de conexiones abiertas mantenidas por el pool de conexiones
connector.pool_connection_manager.maxtotalopenconnections=200
# Maximo de conexiones por defecto para un host y puerto
connector.pool_connection_manager.defaultmaxconnectionsperroute=10
# Maximo de conexiones para un host y puerto
connector.pool_connection_manager.maxconnectionshostnameport=50

# Alias a verificar en el fichero Trustore.
connector.truststore.alias.test=testservicios.pge.red.uy
connector.truststore.alias.prod=servicios.pge.red.uy
